// Microduck XR service worker (generated by build.py from src/sw.js): keeps the engines, model and policies on the
// device so later visits start at once and work offline.
//  - assets/ files are pinned versions: served from the cache, fetched once
//  - the page itself: network first, the cached copy when offline
//  - "precache" (sent by the page once every policy has loaded) fills in what this visit did not use
const CACHE = "microduck-xr-281974e395";
const ASSETS = [
 "assets/lib/meshoptimizer/meshopt_simplifier.module.js",
 "assets/lib/mujoco/mujoco.js",
 "assets/lib/mujoco/mujoco.wasm",
 "assets/lib/onnxruntime-web/dist/ort-wasm-simd-threaded.mjs",
 "assets/lib/onnxruntime-web/dist/ort-wasm-simd-threaded.wasm",
 "assets/lib/onnxruntime-web/dist/ort.wasm.min.mjs",
 "assets/lib/three/build/three.core.js",
 "assets/lib/three/build/three.module.js",
 "assets/lib/three/examples/jsm/controls/OrbitControls.js",
 "assets/lib/three/examples/jsm/lines/LineMaterial.js",
 "assets/lib/three/examples/jsm/lines/LineSegments2.js",
 "assets/lib/three/examples/jsm/lines/LineSegmentsGeometry.js",
 "assets/lib/three/examples/jsm/loaders/GLTFLoader.js",
 "assets/lib/three/examples/jsm/loaders/STLLoader.js",
 "assets/lib/three/examples/jsm/utils/BufferGeometryUtils.js",
 "assets/lib/three/examples/jsm/utils/SkeletonUtils.js",
 "assets/lib/webxr-input-profiles/dist/profiles/generic-hand/left.glb",
 "assets/lib/webxr-input-profiles/dist/profiles/generic-hand/right.glb",
 "assets/microduck/policies/BEST_alpha_sitstand.onnx",
 "assets/microduck/policies/BEST_alpha_stand.onnx",
 "assets/microduck/policies/BEST_alpha_walking.onnx",
 "assets/microduck/policies/BEST_roller.onnx",
 "assets/microduck/policies/BEST_roller_crouch.onnx",
 "assets/microduck/policies/alpha_ground_pick.onnx",
 "assets/microduck/policies/ball_kick_left.onnx",
 "assets/microduck/policies/ball_kick_right.onnx",
 "assets/microduck/policies/roulade.onnx",
 "assets/microduck/robot/mjlab/kinematics.json",
 "assets/microduck/robot/mjlab/kinematics_rollers.json",
 "assets/microduck/robot/mjlab/meshes/ankle_l_v1.stl",
 "assets/microduck/robot/mjlab/meshes/ankle_r_v1.stl",
 "assets/microduck/robot/mjlab/meshes/rim.stl",
 "assets/microduck/robot/mjlab/meshes/roller_blade.stl",
 "assets/microduck/robot/mjlab/meshes/tire.stl",
 "assets/microduck/robot/mjlab/microduck.glb",
 "assets/microduck/robot/mjlab/robot_allcollisions.xml",
 "assets/microduck/robot/mjlab/robot_allcollisions_rollers.xml"
];

self.addEventListener("install", () => self.skipWaiting());
self.addEventListener("activate", (e) => e.waitUntil((async () => {
  for (const k of await caches.keys()) if (k.startsWith("microduck-xr-") && k !== CACHE) await caches.delete(k);
  await self.clients.claim();
})()));

const base = () => new URL("./", self.registration.scope).href;

self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET" || !req.url.startsWith(base())) return;
  const asset = req.url.startsWith(base() + "assets/");
  e.respondWith(caches.open(CACHE).then(async (c) => {
    if (asset) {
      const hit = await c.match(req, { ignoreSearch: true });
      if (hit) return hit;
      const r = await fetch(req);
      if (r.ok) c.put(req, r.clone());
      return r;
    }
    try {
      const r = await fetch(req);
      if (r.ok && req.mode === "navigate") c.put(base(), r.clone());
      return r;
    } catch (err) {
      const hit = req.mode === "navigate" ? await c.match(base()) : await c.match(req);
      if (hit) return hit;
      throw err;
    }
  }));
});

self.addEventListener("message", (e) => {
  if (e.data !== "precache") return;
  e.waitUntil(caches.open(CACHE).then(async (c) => {
    for (const f of ["", ...ASSETS]) {
      const url = base() + f;
      if (!(await c.match(url))) await c.add(url).catch(() => {});
    }
  }));
});
