// Microduck XR service worker (generated by build.py from src/sw.js): keeps the engines, model and policies on the
// device so later visits start at once and work offline.
//  - assets/ files are pinned versions: served from the cache, fetched once
//  - the page itself: network first, the cached copy when offline
//  - "precache" (sent by the page once every policy has loaded) fills in what this visit did not use
const CACHE = "__CACHE__";
const ASSETS = __ASSETS__;

self.addEventListener("install", () => self.skipWaiting());
self.addEventListener("activate", (e) => e.waitUntil((async () => {
  for (const k of await caches.keys()) if (k.startsWith("microduck-xr-") && k !== CACHE) await caches.delete(k);
  await self.clients.claim();
})()));

const base = () => new URL("./", self.registration.scope).href;

self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET" || !req.url.startsWith(base())) return;
  const asset = req.url.startsWith(base() + "assets/");
  e.respondWith(caches.open(CACHE).then(async (c) => {
    if (asset) {
      const hit = await c.match(req, { ignoreSearch: true });
      if (hit) return hit;
      const r = await fetch(req);
      if (r.ok) c.put(req, r.clone());
      return r;
    }
    try {
      const r = await fetch(req);
      if (r.ok && req.mode === "navigate") c.put(base(), r.clone());
      return r;
    } catch (err) {
      const hit = req.mode === "navigate" ? await c.match(base()) : await c.match(req);
      if (hit) return hit;
      throw err;
    }
  }));
});

self.addEventListener("message", (e) => {
  if (e.data !== "precache") return;
  e.waitUntil(caches.open(CACHE).then(async (c) => {
    for (const f of ["", ...ASSETS]) {
      const url = base() + f;
      if (!(await c.match(url))) await c.add(url).catch(() => {});
    }
  }));
});
